### ISSUE TITLE
Unicode escape sequences in the json data

### ISSUE THREAD

**Issue by bmosaicml** [ruixiangcui/AGIEval#17]
If you inspect aqua-rat.jsonl (and other datasets), there are unicode escape sequences throughout the data.

```
{"passage": null, "question": "A car is being driven, in a straight line and at a uniform speed, towards the base of a vertical tower. The top of the tower is observed from the car and, in the process, it takes 10 minutes for the angle of elevation to change from 45\u00b0 to 60\u00b0. After how much more time will this car reach the base of the tower?", "options": ["(A)5(\u221a3 + 1)", "(B)6(\u221a3 + \u221a2)", "(C)7(\u221a3 \u2013 1)", "(D)8(\u221a3 \u2013 2)", "(E)None of these"], 
```

This can be prevented by going back to the original script you used to write out the data and adding ensure_ascii=False and encode('utf-8') before writing to your file, like so:

`f.write(json.dumps(row, ensure_ascii=False)+ '\n').encode('utf8'))`

**Comment by ruixiangcui** [comment]
Hi @bmosaicml , We have already fixed it. Thank you very much for the notice!
