### ISSUE TITLE
 Many "passage" fields in agieval dataset are empty

### ISSUE THREAD

**Issue by hanjr92** [ruixiangcui/AGIEval#19]
![image](https://github.com/ruixiangcui/AGIEval/assets/73918561/0b0e3c7a-8340-4a21-8ea5-e7d79bf4e304)

**Comment by hanjr92** [comment]
Can't find where the horizontal line is in the text. = =!

**Comment by ruixiangcui** [comment]
Thanks for noticing! I found five entries missing the passage field, and I just fixed it. Please pull to get the latest data.
