### ISSUE TITLE
There is a format error in the data, and an error may be reported when parsing json. In addition, it is strongly recommended to clean the data to provide users with higher quality evaluation data.

### ISSUE THREAD

**Issue by FrankMinions** [ruixiangcui/AGIEval#26]
[https://github.com/ruixiangcui/AGIEval/blob/main/data/v1/gaokao-chemistry.jsonl#L75](url)
 `{"passage": null, "question": "水溶液呈酸性的是( $)$", "options": ["(A)$\\mathrm{NaCl}$", "(B)$\\mathrm{NaHSO}_{4}$", "(C)HCOONa", "(D)$\mathrm{NaHCO}_{3}"], "label": "B", "answer": null, "other": {"source": "2020年浙江省高考化学【7月】"}}
`
Option D is missing a backslash `\`

**Comment by ruixiangcui** [comment]
Hi @FrankMinions, we have re-annotated all gaokao chemistry, biology and physics datasets and added questions from 2023. You can download them on the GitHub page already. Thank you very much again for your usage and support for open-source research!
